name: Build and Release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name "QR_Generator" --version-file=version_info.txt qr_generator.py
    
    - name: Test executable
      run: |
        if (Test-Path "dist/QR_Generator.exe") {
          Write-Host "✓ Executable created successfully"
          Get-ChildItem "dist/QR_Generator.exe" | Format-List Name, Length
        } else {
          Write-Error "✗ Executable not found"
          exit 1
        }
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: QR_Generator-Windows
        path: dist/QR_Generator.exe
    
    - name: Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/QR_Generator.exe
        body: |
          ## QR Code Generator ${{ github.ref_name }}
          
          ### Изменения
          - Автоматическая сборка через GitHub Actions
          - Исправления и улучшения
          
          ### Установка
          1. Скачайте `QR_Generator.exe`
          2. Запустите файл
          3. Никаких дополнительных установок не требуется
          
          ### Системные требования
          - Windows 10/11
          - Разрешения на создание файлов и папок
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}